<a href="https://colab.research.google.com/github/SaitoInmortal/matrizLU/blob/main/ejemploCompleto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
import random
print("factorizacion LU")
n = int(input("ingrese el numero de filaz y columnas para la matriz nxn: "))
matriz = np.zeros([n,n])
l = np.identity(n)
u = np.zeros([n,n])
for f in range(0,n):
  for c in range(0,n):
    matriz[f,c]=input("Ingrese el elemento ("+ str(f+1) +","+str(c+1) +") de la matriz: ")
    #matriz[f,c]=random.randint(-10, 10)
    matriz[f,c]=float(matriz[f,c])
    u[f,c]=matriz[f,c]
for i in range(0,n):
  for j in range(0,n):
    if(i<j):
      factor=u[j,i]/u[i,i]
      l[j,i]=factor
      for k in range(0,n):
        u[j,k]=u[j,k]-(factor*u[i,k])
print(matriz)
print(l)
print(u)

factorizacion LU
ingrese el numero de filaz y columnas para la matriz nxn: 3
[[-3. -2.  9.]
 [-8.  3. -8.]
 [ 8. -5.  8.]]
[[ 1.          0.          0.        ]
 [ 2.66666667  1.          0.        ]
 [-2.66666667 -1.24        1.        ]]
[[ -3.          -2.           9.        ]
 [  0.           8.33333333 -32.        ]
 [  0.           0.          -7.68      ]]
