<a href="https://colab.research.google.com/github/SaitoInmortal/matrizLU/blob/main/Matrizpasopaso.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
import numpy as np
import random
print("factorizacion LU")

factorizacion LU


In [61]:
n = int(input("ingrese el numero de filaz y columnas para la matriz nxn: "))

ingrese el numero de filaz y columnas para la matriz nxn: 3


In [63]:
matriz = np.zeros([n,n])
l = np.identity(n)
u = np.zeros([n,n])
for f in range(0,n):
  for c in range(0,n):
    matriz[f,c]=input("Ingrese el elemento ("+ str(f+1) +","+str(c+1) +") de la matriz: ")
    #matriz[f,c]=random.randint(-10, 10)
    matriz[f,c]=float(matriz[f,c])
    u[f,c]=matriz[f,c]

Ingrese el elemento (1,1) de la matriz: 4
Ingrese el elemento (1,2) de la matriz: -2
Ingrese el elemento (1,3) de la matriz: 1
Ingrese el elemento (2,1) de la matriz: 20
Ingrese el elemento (2,2) de la matriz: -7
Ingrese el elemento (2,3) de la matriz: 12
Ingrese el elemento (3,1) de la matriz: -8
Ingrese el elemento (3,2) de la matriz: 13
Ingrese el elemento (3,3) de la matriz: 17


In [64]:
for i in range(0,n):
  for j in range(0,n):
    if(i<j):
      factor=(matriz[j,i]/matriz[i,i])
      l[j,i]=factor
      for k in range(0,n):
        u[j,k]=u[j,k]-(factor*u[i,k])

In [65]:
print(matriz)

[[ 4. -2.  1.]
 [20. -7. 12.]
 [-8. 13. 17.]]


In [66]:
print(l)

[[ 1.          0.          0.        ]
 [ 5.          1.          0.        ]
 [-2.         -1.85714286  1.        ]]


In [67]:
print(u)

[[ 4.         -2.          1.        ]
 [ 0.          3.          7.        ]
 [ 0.         14.57142857 32.        ]]
